using System;
using System.Collections.Generic;
using System.IO;
using YamlDotNet.RepresentationModel;
using YamlDotNet.Serialization;

namespace NpcValheim.Persistence
{
    /// <summary>
    /// Everything about one NPC's look and type-specific settings, in a shape meant to be
    /// hand-edited on disk (YAML) as much as generated by the in-game admin menu. This is
    /// both what gets written to `npcs/instances/&lt;id&gt;.yaml` (a live mirror of one placed
    /// NPC, auto-updated whenever an admin changes anything) and what gets written to
    /// `npcs/templates/&lt;name&gt;.yaml` when an admin saves the current NPC as a reusable
    /// preset -- same shape, different purpose.
    /// </summary>
    public class NpcProfile
    {
        /// <summary>
        /// Exact keys that existed in the source YAML. YamlDotNet necessarily fills missing
        /// value-type properties with 0/false and our initializers create empty collections,
        /// so the object alone cannot tell `scale` omitted from `scale: 1`, or `sells`
        /// omitted from `sells: []`. Template application is a patch, and needs that
        /// distinction. Programmatically-created profiles have no presence map and retain
        /// the historical full-profile behavior.
        /// </summary>
        [YamlIgnore]
        internal NpcProfilePresence Presence { get; set; }

        public string Name { get; set; } = "NPC";

        /// <summary>
        /// Which kind of NPC this profile was made for -- "Marketplace", "Auction",
        /// "Teleporter", "Mailbox", "QuestGiver", or empty for one that suits any of them.
        ///
        /// Without it the admin panel offered every saved template to every NPC, so applying
        /// a travel network to a merchant was one wrong click away. A look can be shared; a
        /// merchant's price list on a teleporter is nonsense.
        /// </summary>
        public string ForType { get; set; } = "";

        /// <summary>Slot name (ArmorSlot.ToString()) -> item prefab name. Missing/empty means
        /// nothing equipped in that slot.</summary>
        public Dictionary<string, string> Armor { get; set; } = new Dictionary<string, string>();

        public string Hair { get; set; } = "";
        public string Beard { get; set; } = "";
        public int Model { get; set; } = 0;

        /// <summary>Legacy numbered presets remain for backward-compatible YAML files.
        /// New profiles also store the exact RGB values below.</summary>
        public int SkinPreset { get; set; } = 0;
        public int HairColorPreset { get; set; } = 0;
        public RgbColor SkinColor { get; set; }
        public RgbColor HairColor { get; set; }
        public string RightHand { get; set; } = "";
        public string LeftHand { get; set; } = "";
        public float Scale { get; set; } = 1f;

        // Null when not applicable to the NPC type -- keeps a Teleporter's yaml free of
        // marketplace noise and vice versa.
        public TeleporterSettings Teleporter { get; set; }
        public MarketplaceSettings Marketplace { get; set; }
        public QuestGiverSettings QuestGiver { get; set; }

        internal bool HasExplicitPresence => Presence != null;

        internal bool HasField(string name) => Presence == null || Presence.Root.Contains(name);

        /// <summary>
        /// Produces the view consumed by the existing type-specific handlers. Missing
        /// members remain null (leave current state alone); an explicitly empty list is
        /// represented as a single ignored sentinel so legacy handlers enter their replace
        /// branch and persist an empty value. This keeps the wire/ZDO shape compatible while
        /// giving YAML the normal patch semantics: omitted = preserve, [] = clear.
        /// </summary>
        internal NpcProfile TypeSpecificApplication(NpcProfile current)
        {
            if (Presence == null) return this;

            var result = new NpcProfile
            {
                Name = Name,
                ForType = ForType,
                Marketplace = null,
                Teleporter = null,
                QuestGiver = null,
            };

            if (HasField("marketplace") && Marketplace != null)
            {
                var existing = current?.Marketplace;
                result.Marketplace = new MarketplaceSettings
                {
                    TaxPercent = Presence.Marketplace.Contains("taxPercent")
                        ? Marketplace.TaxPercent
                        : existing?.TaxPercent ?? 0,
                    Buys = PriceListForApplication(Marketplace.Buys,
                        Presence.Marketplace.Contains("buys")),
                    Sells = PriceListForApplication(Marketplace.Sells,
                        Presence.Marketplace.Contains("sells")),
                };
            }

            if (HasField("teleporter") && Teleporter != null)
            {
                var existing = current?.Teleporter;
                result.Teleporter = new TeleporterSettings
                {
                    CostItem = Presence.Teleporter.Contains("costItem")
                        ? Teleporter.CostItem
                        : existing?.CostItem ?? "",
                    CostAmount = Presence.Teleporter.Contains("costAmount")
                        ? Teleporter.CostAmount
                        : existing?.CostAmount ?? 0,
                    CooldownSeconds = Presence.Teleporter.Contains("cooldownSeconds")
                        ? Teleporter.CooldownSeconds
                        : existing?.CooldownSeconds ?? 0f,
                    Destinations = DestinationListForApplication(Teleporter.Destinations,
                        Presence.Teleporter.Contains("destinations")),
                };
            }

            if (HasField("questGiver") && QuestGiver != null)
            {
                bool specified = Presence.QuestGiver.Contains("quests");
                result.QuestGiver = new QuestGiverSettings
                {
                    // The current quest-giver contract uses an empty ZDO string for its
                    // default/all catalog. A blank sentinel reaches that state through the
                    // legacy handler; an omitted key stays null and does nothing.
                    Quests = !specified ? null : QuestGiver.Quests != null && QuestGiver.Quests.Count > 0
                        ? QuestGiver.Quests
                        : new List<string> { "" },
                };
            }

            return result;
        }

        private static List<ShopPrice> PriceListForApplication(List<ShopPrice> source, bool specified)
        {
            if (!specified) return null;
            return source != null && source.Count > 0 ? source : new List<ShopPrice> { null };
        }

        private static List<TeleportDestinationSettings> DestinationListForApplication(
            List<TeleportDestinationSettings> source, bool specified)
        {
            if (!specified) return null;
            return source != null && source.Count > 0
                ? source
                : new List<TeleportDestinationSettings> { null };
        }
    }

    /// <summary>Presence map populated from the YAML representation before defaults erase
    /// the distinction between an omitted key and an explicitly empty/default value.</summary>
    internal sealed class NpcProfilePresence
    {
        internal readonly HashSet<string> Root = Keys();
        internal readonly HashSet<string> Marketplace = Keys();
        internal readonly HashSet<string> Teleporter = Keys();
        internal readonly HashSet<string> QuestGiver = Keys();

        internal static NpcProfilePresence Read(string yaml)
        {
            var result = new NpcProfilePresence();
            var stream = new YamlStream();
            stream.Load(new StringReader(yaml ?? ""));
            if (stream.Documents.Count == 0 || !(stream.Documents[0].RootNode is YamlMappingNode root))
                return result;

            AddKeys(root, result.Root);
            AddNestedKeys(root, "marketplace", result.Marketplace);
            AddNestedKeys(root, "teleporter", result.Teleporter);
            AddNestedKeys(root, "questGiver", result.QuestGiver);
            return result;
        }

        private static void AddNestedKeys(YamlMappingNode root, string key, HashSet<string> target)
        {
            foreach (var pair in root.Children)
            {
                if (!(pair.Key is YamlScalarNode scalar) ||
                    !string.Equals(scalar.Value, key, StringComparison.OrdinalIgnoreCase) ||
                    !(pair.Value is YamlMappingNode mapping)) continue;

                AddKeys(mapping, target);
                return;
            }
        }

        private static void AddKeys(YamlMappingNode mapping, HashSet<string> target)
        {
            foreach (var key in mapping.Children.Keys)
                if (key is YamlScalarNode scalar && !string.IsNullOrEmpty(scalar.Value))
                    target.Add(scalar.Value);
        }

        private static HashSet<string> Keys() =>
            new HashSet<string>(StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Which quests one quest giver offers.
    ///
    /// Every giver used to offer every quest in the folder, so two NPCs standing in different
    /// villages were interchangeable. Putting the list in the profile makes a giver a
    /// character with something of their own to ask for -- and because it lives in the
    /// profile, that whole set is saved and re-applied as one reusable template.
    /// </summary>
    public class QuestGiverSettings
    {
        /// <summary>Quest ids (the yaml file names). An empty list means "everything in the
        /// folder", which is what an NPC does before anyone has configured it.</summary>
        public List<string> Quests { get; set; } = new List<string>();
    }

    public class RgbColor
    {
        /// <summary>Normalized RGB components in the 0..1 range.</summary>
        public float R { get; set; }
        public float G { get; set; }
        public float B { get; set; }
    }

    public class TeleporterSettings
    {
        public string CostItem { get; set; } = "";
        public int CostAmount { get; set; } = 0;
        public float CooldownSeconds { get; set; } = 0f;

        /// <summary>Every place this teleporter can send you. Part of the profile, so a
        /// whole travel network can be saved as a template and re-applied to another NPC.</summary>
        public List<TeleportDestinationSettings> Destinations { get; set; } = new List<TeleportDestinationSettings>();
    }

    /// <summary>One entry in a teleporter's destination list. Rotation is kept as a yaw in
    /// degrees rather than a quaternion purely so the yaml stays something a human can edit.</summary>
    public class TeleportDestinationSettings
    {
        public string Id { get; set; } = "";
        public string Name { get; set; } = "";
        public float X { get; set; }
        public float Y { get; set; }
        public float Z { get; set; }
        public float Yaw { get; set; }

        /// <summary>Price of this route, in units of <see cref="CostItem"/>.</summary>
        public int Cost { get; set; } = 0;

        /// <summary>The item this route is paid in. Empty means the teleporter's default
        /// item, which is what every route saved before this field existed meant.</summary>
        public string CostItem { get; set; } = "";
    }

    public class MarketplaceSettings
    {
        /// <summary>Percentage of each player-to-player sale kept as tax instead of paid to
        /// the seller.</summary>
        public int TaxPercent { get; set; } = 0;

        /// <summary>What this merchant buys directly from players, and for how much each.
        /// Separate from the auction house: this is the NPC's own money, paid instantly, and
        /// it gives a price floor so nobody is stuck holding unsellable stock.</summary>
        public List<ShopPrice> Buys { get; set; } = new List<ShopPrice>();

        /// <summary>What this merchant offers for sale, and for how much each.</summary>
        public List<ShopPrice> Sells { get; set; } = new List<ShopPrice>();
    }

    public class ShopPrice
    {
        public string ItemName { get; set; } = "";
        public int Price { get; set; } = 0;
    }
}
