using System.Collections.Generic;

namespace NpcValheim.Persistence
{
    /// <summary>
    /// Everything about one NPC's look and type-specific settings, in a shape meant to be
    /// hand-edited on disk (YAML) as much as generated by the in-game admin menu. This is
    /// both what gets written to `npcs/instances/&lt;id&gt;.yaml` (a live mirror of one placed
    /// NPC, auto-updated whenever an admin changes anything) and what gets written to
    /// `npcs/templates/&lt;name&gt;.yaml` when an admin saves the current NPC as a reusable
    /// preset -- same shape, different purpose.
    /// </summary>
    public class NpcProfile
    {
        public string Name { get; set; } = "NPC";

        /// <summary>Slot name (ArmorSlot.ToString()) -> item prefab name. Missing/empty means
        /// nothing equipped in that slot.</summary>
        public Dictionary<string, string> Armor { get; set; } = new Dictionary<string, string>();

        public string Hair { get; set; } = "";
        public string Beard { get; set; } = "";
        public int Model { get; set; } = 0;

        /// <summary>Legacy numbered presets remain for backward-compatible YAML files.
        /// New profiles also store the exact RGB values below.</summary>
        public int SkinPreset { get; set; } = 0;
        public int HairColorPreset { get; set; } = 0;
        public RgbColor SkinColor { get; set; }
        public RgbColor HairColor { get; set; }
        public string RightHand { get; set; } = "";
        public string LeftHand { get; set; } = "";
        public float Scale { get; set; } = 1f;

        // Null when not applicable to the NPC type -- keeps a Teleporter's yaml free of
        // marketplace noise and vice versa.
        public TeleporterSettings Teleporter { get; set; }
        public MarketplaceSettings Marketplace { get; set; }
    }

    public class RgbColor
    {
        /// <summary>Normalized RGB components in the 0..1 range.</summary>
        public float R { get; set; }
        public float G { get; set; }
        public float B { get; set; }
    }

    public class TeleporterSettings
    {
        public string CostItem { get; set; } = "";
        public int CostAmount { get; set; } = 0;
        public float CooldownSeconds { get; set; } = 0f;

        /// <summary>Every place this teleporter can send you. Part of the profile, so a
        /// whole travel network can be saved as a template and re-applied to another NPC.</summary>
        public List<TeleportDestinationSettings> Destinations { get; set; } = new List<TeleportDestinationSettings>();
    }

    /// <summary>One entry in a teleporter's destination list. Rotation is kept as a yaw in
    /// degrees rather than a quaternion purely so the yaml stays something a human can edit.</summary>
    public class TeleportDestinationSettings
    {
        public string Id { get; set; } = "";
        public string Name { get; set; } = "";
        public float X { get; set; }
        public float Y { get; set; }
        public float Z { get; set; }
        public float Yaw { get; set; }

        /// <summary>Price of this route, in units of the teleporter's cost item.</summary>
        public int Cost { get; set; } = 0;
    }

    public class MarketplaceSettings
    {
        /// <summary>Percentage of each player-to-player sale kept as tax instead of paid to
        /// the seller.</summary>
        public int TaxPercent { get; set; } = 0;

        /// <summary>What this merchant buys directly from players, and for how much each.
        /// Separate from the auction house: this is the NPC's own money, paid instantly, and
        /// it gives a price floor so nobody is stuck holding unsellable stock.</summary>
        public List<ShopPrice> Buys { get; set; } = new List<ShopPrice>();

        /// <summary>What this merchant offers for sale, and for how much each.</summary>
        public List<ShopPrice> Sells { get; set; } = new List<ShopPrice>();
    }

    public class ShopPrice
    {
        public string ItemName { get; set; } = "";
        public int Price { get; set; } = 0;
    }
}
